# Configuration for dependabot - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `containers/` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Apply labels to all pull requests for Docker updates
    labels:
      - "dependencies"
      - "docker"
    # Group updates together where possible (e.g., multiple containers using same base image)
    groups:
      docker-base-images:
        patterns:
          - "*"
    # Open pull requests for version updates even when there are already open pull requests
    open-pull-requests-limit: 10
    # Commit message preferences
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"
    # Ignore major version updates by default (uncomment to enable)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Configuration for GitHub Actions (commented out by default)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
# Note: This configuration will scan all Dockerfiles in the repository for updates.
# It will create pull requests when new versions of base images are available.
# Review and adjust the settings according to your needs.
